version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: zarovdeveloper/taski_backend:1.1
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: zarovdeveloper/taski_frontend:1.0
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: zarovdeveloper/taski_gateway:1.0
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
